### ISSUE TITLE
No repository for this project

### ISSUE THREAD

**Issue by BlaM** [UltimateBrent/hg-commit#1]
hg-commit keeps telling me that there is no repository for this project whenever I try to use it. I'v tried with many different projects - but always the same result.

![image](https://cloud.githubusercontent.com/assets/176011/11526815/60b15e78-98dd-11e5-9968-3c20a4b9a3f2.png)

- OS: Windows 8
- hg.exe coming from TortoiseHG
- Hg Path is `"C:\Program Files\TortoiseHg\hg.exe"` (includes quotes - does not find hg.exe without them)

**Comment by UltimateBrent** [comment]
Well I'm like 5 months late, but this is saying there's no .hg folder in your project. It's finding the hg.exe just fine.

**Comment by BlaM** [comment]
So what do I do if there IS a .hg folder?

**Comment by UltimateBrent** [comment]
Make sure the .hg folder is in the project on the base level, and if that doesn't work, I'd open the dev console and see what's being popped out over there. **View > Developer > Toggle Developer Tools** It'll output the raw hg response.
